# Undertone rustfmt configuration
edition = "2024"
max_width = 100
use_small_heuristics = "Max"
reorder_imports = true
reorder_modules = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
